<!-- Generated by adapters/build.sh from skills/*/SKILL.md. Edit those files, not this one. -->

## Skill: eval-driven-prompt-tuning

Improve an LLM pipeline's accuracy against a labelled evaluation set when you may change prompts but not models or code. Use when given a target metric, a fixed dataset, a baseline to beat, and a list of ranked defects — or whenever asked to raise extraction/classification/mapping accuracy without retraining. Covers validating the scoring harness, diagnosing from existing run artifacts before spending API calls, measuring run-to-run variance, and handling labels that turn out to be wrong.


# Eval-driven prompt tuning

> **Status: Beta.** Still being tested against real runs — the steps are solid but expect refinements.

For work shaped like: *here is a pipeline at X% on a labelled set, here are the ranked defects,
raise it without touching the model or the code.*

The failure mode this skill exists to prevent is **spending a day fixing a defect that was never
real**, because the baseline was measured under a configuration nobody verified.

## The order that matters

1. Validate the scoring harness against the published baseline.
2. Verify what configuration the baseline actually ran under.
3. Diagnose every defect from existing artifacts, before any new run.
4. Measure run-to-run variance.
5. Only then change anything.

Steps 1, 2 and 4 are the ones people skip, and each one silently invalidates everything after it.


## 1. Reproduce the baseline before touching anything

Write your own scorer, run it on the **published output artifacts**, and check it reproduces the
published number **exactly — per item and in total**. Not approximately. If your scorer says 90.6%
and the report says 90.7%, find the difference before continuing; that gap is a bug in your
understanding of the metric, and every later delta inherits it.

Things that are routinely wrong on the first attempt:

- **Which fields are scored.** Derived/computed rows are often excluded. Count the scored fields
  and check the total matches the report's denominator exactly.
- **How records align to periods/columns.** Do not trust a column's stored index or label. Detect
  the meaningful columns structurally, and check every record — a minority of documents carry an
  extra leading column and silently shift.
- **Null vs zero.** A produced `0` may count as "no value" in the reference convention.
- **Tolerance.** If the report counts ±1 differences as errors, your scorer must too. A tolerance
  you invented inflates the score.

Only when per-item numbers match is the harness trustworthy.

## 2. Verify the baseline's configuration, not just its numbers

**A baseline is a number plus the configuration that produced it. You were given the number.**

Check, explicitly:

- Does the working tree match the deployed branch? Checkouts left on experiment branches are
  normal and invisible.
- Does the runtime config (model, parameters, prompt templates) match production?
- Does any prompt content live **outside** the repo — in a database table, a CSV, a config
  service? If so, does the local copy match production's copy?
- Was the baseline produced on production, or on a developer machine that may have carried local
  edits?

If you cannot verify production's state, say so and name the single query or check that would
settle it. Do not infer it from a file in the repo that *looks* authoritative — a preserved
"ORIGINAL" backup and the live edited file can differ on exactly the field in dispute.

Then **run your own control**: the untouched production configuration, scored by your validated
harness. That control, not the published number, is what your changes get compared against.

## 3. Diagnose from existing artifacts — spend zero API calls

If you have the model's previous output and the labels, every defect can usually be root-caused
before running anything.

**Recover the label's derivation, not just its value.** The label says an item should be 101,532;
it does not say why. Search the source records for the combination that produces it — subset-sum
over candidate lines works well for aggregation tasks. Do this across every item in the set:

- A rule confirmed on **all** items is safe to encode.
- A rule seen on **one** item is an anecdote. Record it; do not encode it.

Over-generalising from a single example is the most expensive mistake available here. If a defect
you were handed traces back to a prior session doing exactly that, say so — the fix is a revert,
not a new rule.

**Check the arithmetic of each error.** A shortfall that exactly equals one source line names its
own cause. Differences of 1–2 units usually mean summed components where a printed total was
wanted (independent rounding), not a mapping error.

## 4. Find every surface that carries instructions

Guidance is rarely in one file. Typically:

- the prompt template
- few-shot exemplars (**including their explanatory notes** — these are instructions and are
  frequently the strongest signal)
- per-item descriptions injected into the prompt from data
- rules embedded in the schema or field documentation

**These contradict each other more often than not.** Enumerate all of them for the item you are
fixing before writing anything, and check whether the thing you are about to "fix" is already
stated correctly somewhere and being overridden elsewhere. Note which surfaces are in scope for
you to change — if the decisive one is out of scope, say so and escalate rather than writing a
rule that will lose the fight.

## 5. Measure variance before attributing any delta

Run the **same configuration** two or three times. Temperature 0 does not mean deterministic.

Establish the noise floor before interpreting any result. A single run at this kind of scale can
easily swing by several per cent. Without the noise floor you will confidently attribute an
improvement, or a regression, to a change that caused neither.

Watch for **intermittent truncated output** — the model occasionally returns a short, valid
response that omits most of its answer, with no error logged. This costs a block of fields at once
and is the usual source of large swings. It is a reliability defect worth reporting separately
from accuracy, with a cheap fix (retry when the output size is implausibly small).

Quote a **range or median across runs**, never the best run. Reporting the luckiest of three is
cherry-picking even when unintentional.

## 6. Change one mechanism at a time

**Name the mechanism, not the symptom.** A symptom fix addresses one item; a mechanism fix
addresses every item sharing the cause. If a fix targeting a defect does not move it, you have the
wrong mechanism — re-diagnose rather than adding another rule.

A useful sign you have found the real mechanism: one correction resolves several apparently
unrelated defects at once.

After each change, compare **per-item error counts** against the control, not just the headline:

- errors removed
- errors introduced
- items unchanged

**Revert anything that does not earn its place.** A change that fixes one item and breaks another
of similar severity is a net loss; so is one whose gain is inside the noise floor.

Run only the subset that exercises the change, then a clean full run at the end. Be careful
deriving the subset: include every item the changed rule *could* touch, not only those that
currently fail.

## 7. Write rules that generalise

Encode the **convention**, not the answer:

- No entity names, document names, or expected values in prompts or exemplars.
- Domain-shaped examples are fine; answer keys are not.
- If the existing prompt names a specific record, that is a defect — it is both over-fitted and
  often wrong.
- State both directions of a rule. "X belongs here" invites the model to leave the slot empty when
  X is absent; say what to do in the absent case too.
- When two similar cases are treated differently, say the asymmetry is deliberate, or the model
  will regularise it away.

## 8. When the labels are wrong

Labels are produced by people and can be stale or mistaken. When your evidence contradicts a
label:

- Say so, with the exact arithmetic, and name the affected records.
- **Do not edit the labels yourself**, and do not quietly fit the prompt to them either.
- Escalate to whoever owns them.

Expect to be overruled sometimes. When corrected labels arrive, **revert the changes they
invalidate**, re-score every earlier result against the corrected labels, and say plainly that
comparisons made across a label change are void. A baseline and a candidate scored against
different labels cannot be compared — this is easy to do by accident and produces confident
nonsense.

## 9. Trust nothing that looks plausible

Verify that a run **produced output** before scoring it. A pipeline can report success while
writing nothing, and an empty result set scores as a plausible-looking percentage rather than an
obvious zero.

Cheap guards worth running every time:

- Count produced records per item; flag any that are zero or far below the norm.
- Check a completed job actually wrote results.
- Treat a score that exactly matches an earlier known-bad run as a red flag, not a coincidence.

Also beware concurrent runners: re-invoking a batch while one is running produces duplicate work
and corrupted aggregates. Wait for the queue to drain, and deduplicate defensively.

## 10. Reporting

Track per run: what changed, which items ran, tokens/cost, wall time, and per-defect plus overall
accuracy.

In the write-up:

- Quote the control you measured, not the number you were handed, and say which is which.
- State the range across runs and the noise floor.
- Separate **what the change achieved** from **what a data/label correction achieved** — these get
  conflated and inflate the apparent value of the work.
- List defects you deliberately left, with the evidence and why (usually: single-item signal).
- If a defect in the brief turned out not to exist, say so prominently. That is a finding, not an
  embarrassment.

## Scope discipline

If the brief fixes the model, the code, or the parameters, treat a change there as out of scope —
**stop and report instead of doing it**. If asked later to test a model change, note that a newer
model may reject parameters an older one accepted, and that a pipeline often sends those
parameters from several stages, each with its own config and call site; a model swap can be a
multi-file code migration rather than a config edit. Measure before recommending: a larger model
frequently trades gains in one area for losses in another and may not be worth its cost.

Never inspect credentials. If something fails in a way that looks credential-related, report it as
a hypothesis and stop.

## Skill: model-feasibility-study

Run an empirical feasibility study comparing candidate models, libraries or approaches against a decision someone has to make — benchmark several options on real data, measure against recognised standards, and report what the evidence does and does not support. Use when asked 'which model/framework should we use', 'can we build this in-house instead of buying X', 'is this approach good enough', 'benchmark these options', or when a stakeholder wants a build-vs-buy or vendor-replacement recommendation backed by experiment rather than opinion. Covers problem framing, hypothesis, dataset sourcing and provenance, controlled comparison, standards-grade metrics, and a written report. Not for tuning one known model (that is an eval/optimisation task) or for shipping production code.


# Model feasibility study

> **Status: Beta.** Still being tested against real studies — the steps are solid but expect refinements.

A study is evidence for a **decision**, not a benchmark table. Every phase
below exists to make one recommendation defensible in front of whoever has to
act on it.

## Phases

Work them in order. Each gates the next.

### 1. Frame the decision
Write down, before any code:
- **The decision** someone will make with this. If you cannot name it, stop and ask.
- **The claim to test**, falsifiably. "Open-source matching is accurate enough to replace vendor X" beats "evaluate face recognition".
- **The success bar**, in the units of the decision (cost, latency, error rate, effort). If nobody has set one, say so — an unstated bar is the most common reason a study lands and changes nothing.
- **What would falsify it.** Name this now, while you have no stake in the answer.

### 2. Research the landscape
Survey what exists: candidate approaches, what the incumbent/vendor actually
does, and the recognised standards or benchmarks in the field. Note which
standards define the metrics you should report — reporting the field's own
metrics is most of what makes a result credible to an outside reader.

Separate **verified fact** from **vendor marketing** from **your inference**,
and keep them separate in the report too. A capability claim sourced from a
vendor's own sales page is that vendor's claim, not a fact; label it as such.
When a vendor page contains an implausible claim, cite it as the reason to
read the rest sceptically.

### 3. Source data, provenance first
Audit provenance **before** downloading, never after.
- Official project releases, institutional hosts, original authors only.
- Community re-uploads and mirrors are not acceptable even with a caveat — for client-facing work a result traceable to an unverifiable mirror is not defensible, and a caveat is not a remedy.
- If only an unverified source exists: say so and **ask** before pulling it.
- Record licence per dataset. A permissive licence (commercial use allowed) is often the difference between a usable and useless result.
- Keep a `provenance.md`: every model and dataset, its source URL, licence, and how it was obtained.

If a source must be withdrawn, delete the data, the runner code, the derived
results and figures, **and** every reference in the docs — then state plainly
that the experiment was withdrawn. Never let it quietly disappear.

Prefer a small **real** dataset over a large synthetic one for the headline
result; use the large one for statistical resolution the small one cannot
reach.

### 4. Design the comparison
- **Hold everything constant except the one variable.** Share preprocessing, alignment, and input handling across all candidates so the only difference is the thing under test. This is the single biggest driver of whether the comparison means anything.
- **Define metrics before running.** Take them from the field's standard where one exists. Implement them yourself only where no library matches the standard's definition, and **unit-test them against a known-good library** on the cases that overlap.
- **Know your resolution limit.** With *n* comparisons you cannot evidence a rate rarer than roughly 3/*n* (the "rule of 3"). Compute it, state it, and never quote an operating point past it.
- Include a **baseline** and, where the pipeline has stages, an **ablation** showing what each stage costs.

### 5. Run and verify
- Long runs go in the background with logs; check on them rather than blocking.
- **A loud failure is worth more than a plausible number.** Wrong-but-reasonable output is the dangerous failure mode. Sanity-check intermediate artifacts (do any inputs survive preprocessing? are score ranges sane?) before trusting any aggregate.
- Watch for algorithmic blowup between pilot and full scale. Something that takes 2s on 10k rows can be non-terminating at 5M; measure before assuming it will finish.

### 6. Read the results honestly
- **Aggregates hide the user experience.** Check whether failures cluster in a few subjects/inputs rather than spreading evenly — if they do, the mean is misleading and the design consequence (a review tier, a fallback path) is usually the most valuable finding in the study.
- Report where the winner's advantage actually lives. A ranking table often understates a gap that appears only at strict operating points.
- Demographic, subgroup, or fairness breakdowns need sample sizes almost nobody has at pilot scale. Report them for transparency, and state plainly that they support no claim in either direction.

### 7. Report
Write for the decision-maker, then the specialist — not the reverse.

- **Lead with the recommendation and its conditions.**
- **Unbundle the problem.** The requested scope is rarely one thing. Split it into parts and give each a separate verdict; "build this part, keep buying that part" is a frequent and valuable answer.
- **A limitations section is not optional**, and it goes before anyone quotes a number. State what the study is (technology evaluation, pilot) and what it is not (evidence of production performance).
- **Name the unasked question.** Studies usually surface something the brief assumed away — an unquantified cost, an unconfirmed contract scope, a missing requirement. Say it.
- List next steps in priority order, marking which are on the critical path.

Chart for the audience:
- The field's conventional chart (DET, ROC, PR curve) belongs in the technical doc. It answers a specialist's question.
- For everyone else, answer the **business** question directly, in human-scale units: "out of 1,000 real users, how many does each option wrongly block?" A sorted bar chart of that beats any curve.
- If a reader says they do not understand a chart, replace the chart. Do not add explanation to a chart that is wrong for its audience.
- Log axes cannot show zero. Check whether your plot is silently dropping the best result.

## Traps

| Trap | Guard |
|---|---|
| Dataset loader returns floats in [0,1]; casting to uint8 zeroes everything | Print `min/max/dtype/mean` of the first sample before the pipeline |
| Preprocessing silently drops every input | Assert non-empty and log a retention rate at each stage |
| Metric code is O(n²), fine at pilot scale, hangs at full scale | Time it on synthetic data at full scale before the real run |
| Default/most-popular library ≠ best | Always benchmark; the tutorial favourite is often near-worst |
| Quoting an error rate below what the sample can resolve | Compute 3/n, state it, stop there |
| Vendor capability treated as verified | Label marketing claims as claims; read their own pages |
| "Not buildable" applied to a whole category | Split it — one component is often standardised and open |

## Deliverables

```
docs/         00-consolidated (one short doc for the decision-maker)
              01..0N          (per-topic detail)
              provenance.md   (every model + dataset + licence + URL)
              figures/
experiments/  src/            (runners + metrics + metric tests)
              results/        (raw outputs, committed if small)
```

Keep the consolidated doc short enough to read in one sitting. It is the one
that gets read.

