#!/usr/bin/env bash
# Generates per-tool adapters from skills/*/SKILL.md. SKILL.md is the only file
# to hand-edit; everything this script writes is regenerated wholesale on each run.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

mkdir -p .cursor/rules

copilot_file=".github/copilot-instructions.md"
windsurf_file=".windsurfrules"
mkdir -p "$(dirname "$copilot_file")"

{
  echo "<!-- Generated by adapters/build.sh from skills/*/SKILL.md. Edit those files, not this one. -->"
  echo
} > "$copilot_file"

for skill_md in skills/*/SKILL.md; do
  dir="$(dirname "$skill_md")"
  name="$(basename "$dir")"

  description="$(sed -n 's/^description: *//p' "$skill_md" | head -1 | sed -e 's/^"//' -e 's/"$//')"
  body="$(awk '/^---$/{n++; next} n>=2' "$skill_md")"

  # Cursor: thin rule that pulls in the canonical file via @-reference.
  cat > ".cursor/rules/${name}.mdc" <<EOF
---
description: ${description}
alwaysApply: false
---

See @skills/${name}/SKILL.md for the full instructions.
EOF

  # Copilot and Windsurf: no file-include mechanism, so inline the body.
  {
    echo "## Skill: ${name}"
    echo
    echo "${description}"
    echo
    echo "${body}"
    echo
  } >> "$copilot_file"
done

cp "$copilot_file" "$windsurf_file"

echo "Wrote adapters for $(ls skills | wc -l | tr -d ' ') skill(s):"
echo "  .cursor/rules/*.mdc"
echo "  $copilot_file"
echo "  $windsurf_file"
